---
# Copy to config/secrets.yml and encrypt with:
# ansible-vault encrypt config/secrets.yml
pc_user: "replace-me"
pc_password: "replace-me"
registry_username: ""
registry_password: ""
registry_mirror_username: ""
registry_mirror_password: ""

